version: '3.8'

services:
  angular-app:
    container_name: angular-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4302:4302"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: npm run start